.TH APPLY-LICENSE 1  "6 January 2011"
.\" Copyright © 2011 Bart Massey
.\" [This software is released under the "MIT License"]
.\" Please see the file COPYING in the source
.\" distribution of this software for license terms.
.SH NAME
apply-license \- apply a license in a directory
.SH SYNOPSIS
apply-license
.BI [ "<options> ..." ]
.BI [ "license_id" ]
.SH DESCRIPTION
.LP
The apply-license script is used to apply a license to the
source files in a directory.  The script will extract the
relevant information from a license file and apply it to any
source code it can find that does not already appear to have
a copyright notice.  Source code is identified by suffix.
Currently recognized suffixes are
".5c" (Nickle),
".awk",
".c",
".cabal",
".cc" (C++),
".cls" (LaTeX class),
".cpp" (C++),
".css",
".el" (Emacs Lisp),
".h",
".hs",
".html",
".java",
".js" (JavaScript),
".l" (Lex, not lisp),
".lisp" (Common Lisp),
".m" (Matlab/Octave),
".m4",
".man",
".php",
".pl",
".py",
".rb",
".ron" (Rust resource files),
".rs",
".scm" (Scheme),
".sh",
".sty" (LaTeX style),
".tex",
".y" (Yacc);
the files "Makefile"/"makefile" are also processed.
.LP
The first line of a script file may be a "#!" line and is
skipped if so.  The first line of a ".man" file may be a
".TH" line and is skipped if so.
.SH OPTIONS
.TP
.B "-q," "--quick"
This flag "quick-licenses" the project by creating a license
file from the given license id, adding a license note using
"--readme", and setting mode to "none".
.TP
.B "-m," "--mode " [ \fInone\fP | \fIlong\fP | \fIshort\fP | \fIheuristic\fP ]
Indicate the way in which the license will be applied to
source files. In
.I none
mode, the license will not be applied to files.  In
.I long
mode, the license will be applied in full at the end of
all files.  In
.I short
mode, a reference to the license file
will be applied.  In
.I heuristic
mode, each less than twice
the length of the license to be applied will be treated as
short. The default mode is
.IR short .
.TP
.B "-r"
This flag makes apply-license recurse into subdirectories.
.TP
.B "-u," "--username" "<\fIusername\fP>"
Full name of the user copyrighting the files. This is
required unless the environment variable
.B USERNAME
is present.
.TP
.B "-y," "--year" "<\fIyear\fP>"
Copyright year. Defaults to current year.
.TP
.B "-w," "--width" "<\fIwidth\fP>"
Text wrap width. Defaults to 64.
.TP
.B "--readme"
Edit the README to include the license. Chosen README is
README.tpl, README.md, README.txt, README in that order.
If no README exists, README.md will be created.
.TP
.B "--license-filename" "<\fIlicensefile\fP>"
Path to a file containing a license.  Default is LICENSE.txt
or LICENSE or COPYING (in that order) in the current
directory. If none exists, LICENSE.txt will be created.
The
.I "licensefile"
must consist of at least three paragraphs, with paragraphs
separated by a single blank line.  The first paragraph
should contain the copyright notice. The second paragraph
should contain a bracketed license name statement.
Subsequent paragraphs should contain the license text
itself.
.TP
.B "license_id"
Find a file named "license_id" in the license directory and
use that for the license. Incompatible with
.BR "--licensefile" .
.SH BUGS
.LP
Files without a suffix should be heuristically identified
and licensed if possible.
.LP
A file with a copyright already in it is silently
ignored. This can lead to problems if the cruddy
copyright-detection heuristic (currently "is the
word 'copyright' in there?") fails. See
http://github.com/BartMassey/emacs-copyright for an ugly
example.
.SH AUTHOR
Bart Massey <bart@cs.pdx.edu>
