.TH APPLY-LICENSE 1  "2 July 2007"
.\" Copyright (c) 2006-2007 Bart Massey
.\" All Rights Reserved
.\" Please see the end of this file for license information.
.SH NAME
apply-license \- apply a license in a directory
.SH SYNOPSIS
apply-license
.BI [ copying-file ]
.SH DESCRIPTION
.LP
The apply-license script is used to apply a license to the
source files in a directory.  The script will extract the
relevant information from a license file and apply it to any
source code it can find that does not already appear to have
a copyright notice.  Source code is identified by suffix.
Currently recognized suffixes are ".java", ".c", ".h", ".y", ".l",
".css", ".sh", ".awk", ".5c", ".pl", ".rb", ".hs" and ".man"; the file
"Makefile" is also currently processed.  The first line of a
".sh", ".awk", ".5c", ".pl" or ".rb" file must be a "#!" line and
is skipped.  The first line of a ".man" file must be a ".TH"
line and is skipped.  Other files may be added in the
future.
.SH OPTIONS
.TP
.I "copying-file"
Extract copyright information from the license file
.IR "copying-file" .
Default is COPYING in the current directory.
The
.I "copying-file"
must consist of at least three paragraphs, with paragraphs separated by
a single blank line.  The first paragraph should contain the
copyright notice.  The first word of the notice must be the
word "Copyright" with this capitalization; this is used to
detect previously-applied licenses and avoid re-application.
The copyright notice would normally be of the form
.nf

  Copyright (c) 2007 Bart Massey
  ALL RIGHTS RESERVED

.fi
The second paragraph should contain the name of the
license, for example
.nf

  [This is the "MIT license"]

.fi
Subsequent paragraphs should contain the license text
itself.
.SH BUGS
.LP
Empty files are not licensed.  This may not be a bug.
.LP
Each subdirectory must be run separately.  This may not be a bug.
.LP
There should be a file-length below which the license is
referenced rather than included.
.LP
Files without a suffix should be heuristically identified
and licensed if possible.
.SH AUTHOR
Bart Massey <bart@cs.pdx.edu>

.\" Permission is hereby granted, free of charge, to any person
.\" obtaining a copy of this software and associated
.\" documentation files (the "Software"), to deal in the
.\" Software without restriction, including without limitation
.\" the rights to use, copy, modify, merge, publish, distribute,
.\" sublicense, and/or sell copies of the Software, and to
.\" permit persons to whom the Software is furnished to do so,
.\" subject to the following conditions:
.\" 
.\" The above copyright notice and this permission notice shall
.\" be included in all copies or substantial portions of the
.\" Software.
.\" 
.\" THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY
.\" KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
.\" WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR
.\" PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS
.\" OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR
.\" OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR
.\" OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
.\" SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
