.TH APPLY-LICENSE 1  "6 January 2011"
.\" Copyright © 2011 Bart Massey
.\" [This software is released under the "MIT License"]
.\" Please see the file COPYING in the source
.\" distribution of this software for license terms.
.SH NAME
apply-license \- apply a license in a directory
.SH SYNOPSIS
apply-license
.BI [ -s | -l | -h ]
.BI [ -r ]
.BI [ copying-file ]
.SH DESCRIPTION
.LP
The apply-license script is used to apply a license to the
source files in a directory.  The script will extract the
relevant information from a license file and apply it to any
source code it can find that does not already appear to have
a copyright notice.  Source code is identified by suffix.
Currently recognized suffixes are ".java", ".js"
(JavaScript), ".c", ".h", ".y", ".l" (Lex, not lisp),
".lisp" (Common Lisp), ".el" (Emacs Lisp), ".scm" (Scheme), ".css", ".sh",
".awk", ".5c" (Nickle), ".php", ".pl", ".rb", ".hs", ".man",
".tex", ".cls", ".sty", ".m4", ".hs", ".cabal", ".py";
the file "Makefile" is also processed.  The first line
of a ".sh", ".awk", ".5c", ".pl" or ".rb" file must be a
"#!" line and is skipped.  The first line of a ".man" file
must be a ".TH" line and is skipped.  Other files may be
added in the future.
.SH OPTIONS
.TP
.I "-d"
If an existing copyright notice is found in the file, delete
it before proceeding. This is currently very simple and
crude, so check its work afterward.
.TP
.I "-h"
For each "short" file (less than twice the length
of the license to be applied) apply-license will omit the
actual license text and just put a reference to the COPYING
file.  This heuristic is intended as a compromise between
the "-s" and "-l" options.
.TP
.I "-l"
This flag ensures that every file, no matter how
short, contains the full license text.  For the paranoid,
mostly.
.TP
.I "-r"
This flag makes apply-license recurse into subdirectories.
.TP
.I "-s"
This flag (the default) ensures that every file, no
matter how long, contains just a pointer to the license
text.  For those wanting to avoid clutter.
.TP
.I "copying-file"
Extract copyright information from the license file
.IR "copying-file" .
Default is COPYING in the current directory.
The
.I "copying-file"
must consist of at least three paragraphs, with paragraphs
separated by a single blank line.  The first paragraph
should contain the copyright notice.  The notice should
contain the word "Copyright" (preferably in this
capitalization); this is used to detect previously-applied
licenses and avoid re-application, and to detect bogus
copying-files.
.LP
The copyright notice would normally be of the form
.nf

  Copyright \[co] 2011 Bart Massey

.fi
The second paragraph should contain the name of the
license, for example
.nf

  [This is the "MIT license"]

.fi
Subsequent paragraphs should contain the license text
itself.
.SH BUGS
.LP
Empty files are not licensed.  This may not be a bug.
.LP
Files without a suffix should be heuristically identified
and licensed if possible.
.LP
Scripts without #! lines should be processed properly.
.SH AUTHOR
Bart Massey <bart@cs.pdx.edu>
